// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archive.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoreEntry = `-- name: CreateLoreEntry :one
INSERT INTO lore_entries (series_id, title, category, content, metadata, affinity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, series_id, title, category, content, metadata, affinity, search_vec, created_at
`

type CreateLoreEntryParams struct {
	SeriesID pgtype.UUID `json:"series_id"`
	Title    string      `json:"title"`
	Category string      `json:"category"`
	Content  string      `json:"content"`
	Metadata []byte      `json:"metadata"`
	Affinity []string    `json:"affinity"`
}

func (q *Queries) CreateLoreEntry(ctx context.Context, arg CreateLoreEntryParams) (LoreEntry, error) {
	row := q.db.QueryRow(ctx, createLoreEntry,
		arg.SeriesID,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Metadata,
		arg.Affinity,
	)
	var i LoreEntry
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Metadata,
		&i.Affinity,
		&i.SearchVec,
		&i.CreatedAt,
	)
	return i, err
}

const createLoreLink = `-- name: CreateLoreLink :one
INSERT INTO lore_links (source_id, target_id, label, is_revealed)
VALUES ($1, $2, $3, $4)
RETURNING id, source_id, target_id, label, is_revealed, created_at
`

type CreateLoreLinkParams struct {
	SourceID   pgtype.UUID `json:"source_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	Label      pgtype.Text `json:"label"`
	IsRevealed pgtype.Bool `json:"is_revealed"`
}

func (q *Queries) CreateLoreLink(ctx context.Context, arg CreateLoreLinkParams) (LoreLink, error) {
	row := q.db.QueryRow(ctx, createLoreLink,
		arg.SourceID,
		arg.TargetID,
		arg.Label,
		arg.IsRevealed,
	)
	var i LoreLink
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.Label,
		&i.IsRevealed,
		&i.CreatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (title, author, cover_color, description)
VALUES ($1, $2, $3, $4)
RETURNING id, title, author, cover_color, description, created_at
`

type CreateSeriesParams struct {
	Title       string      `json:"title"`
	Author      string      `json:"author"`
	CoverColor  string      `json:"cover_color"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.Title,
		arg.Author,
		arg.CoverColor,
		arg.Description,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.CoverColor,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLoreEntry = `-- name: DeleteLoreEntry :exec
DELETE FROM lore_entries 
WHERE id = $1
`

func (q *Queries) DeleteLoreEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoreEntry, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at FROM admin_users 
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLoreEntriesBySeries = `-- name: GetLoreEntriesBySeries :many
SELECT id, series_id, title, category, content, metadata, affinity, search_vec, created_at FROM lore_entries 
WHERE series_id = $1 
ORDER BY title ASC
`

func (q *Queries) GetLoreEntriesBySeries(ctx context.Context, seriesID pgtype.UUID) ([]LoreEntry, error) {
	rows, err := q.db.Query(ctx, getLoreEntriesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoreEntry
	for rows.Next() {
		var i LoreEntry
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Metadata,
			&i.Affinity,
			&i.SearchVec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoreEntry = `-- name: GetLoreEntry :one
SELECT id, series_id, title, category, content, metadata, affinity, search_vec, created_at FROM lore_entries 
WHERE id = $1
`

func (q *Queries) GetLoreEntry(ctx context.Context, id pgtype.UUID) (LoreEntry, error) {
	row := q.db.QueryRow(ctx, getLoreEntry, id)
	var i LoreEntry
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Metadata,
		&i.Affinity,
		&i.SearchVec,
		&i.CreatedAt,
	)
	return i, err
}

const getRevealedLinksForEntry = `-- name: GetRevealedLinksForEntry :many
SELECT 
    ll.id as link_id,
    ll.label,
    ll.is_revealed,
    le.id as target_entry_id,
    le.title as target_title,
    le.category as target_category
FROM lore_links ll
JOIN lore_entries le ON ll.target_id = le.id
WHERE ll.source_id = $1 AND ll.is_revealed = TRUE
`

type GetRevealedLinksForEntryRow struct {
	LinkID         pgtype.UUID `json:"link_id"`
	Label          pgtype.Text `json:"label"`
	IsRevealed     pgtype.Bool `json:"is_revealed"`
	TargetEntryID  pgtype.UUID `json:"target_entry_id"`
	TargetTitle    string      `json:"target_title"`
	TargetCategory string      `json:"target_category"`
}

func (q *Queries) GetRevealedLinksForEntry(ctx context.Context, sourceID pgtype.UUID) ([]GetRevealedLinksForEntryRow, error) {
	rows, err := q.db.Query(ctx, getRevealedLinksForEntry, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevealedLinksForEntryRow
	for rows.Next() {
		var i GetRevealedLinksForEntryRow
		if err := rows.Scan(
			&i.LinkID,
			&i.Label,
			&i.IsRevealed,
			&i.TargetEntryID,
			&i.TargetTitle,
			&i.TargetCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeries = `-- name: GetSeries :one
SELECT id, title, author, cover_color, description, created_at FROM series 
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id pgtype.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.CoverColor,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, title, author, cover_color, description, created_at FROM series 
ORDER BY title ASC
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.CoverColor,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revealLoreLink = `-- name: RevealLoreLink :one
UPDATE lore_links
SET is_revealed = TRUE
WHERE id = $1
RETURNING id, source_id, target_id, label, is_revealed, created_at
`

func (q *Queries) RevealLoreLink(ctx context.Context, id pgtype.UUID) (LoreLink, error) {
	row := q.db.QueryRow(ctx, revealLoreLink, id)
	var i LoreLink
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.Label,
		&i.IsRevealed,
		&i.CreatedAt,
	)
	return i, err
}

const searchLoreEntries = `-- name: SearchLoreEntries :many
SELECT id, series_id, title, category, content, created_at
FROM lore_entries
WHERE search_vec @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(search_vec, plainto_tsquery('english', $1)) DESC
`

type SearchLoreEntriesRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchLoreEntries(ctx context.Context, plaintoTsquery string) ([]SearchLoreEntriesRow, error) {
	rows, err := q.db.Query(ctx, searchLoreEntries, plaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLoreEntriesRow
	for rows.Next() {
		var i SearchLoreEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoreEntry = `-- name: UpdateLoreEntry :one
UPDATE lore_entries
SET title = $2, category = $3, content = $4, metadata = $5, affinity = $6
WHERE id = $1
RETURNING id, series_id, title, category, content, metadata, affinity, search_vec, created_at
`

type UpdateLoreEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Category string      `json:"category"`
	Content  string      `json:"content"`
	Metadata []byte      `json:"metadata"`
	Affinity []string    `json:"affinity"`
}

func (q *Queries) UpdateLoreEntry(ctx context.Context, arg UpdateLoreEntryParams) (LoreEntry, error) {
	row := q.db.QueryRow(ctx, updateLoreEntry,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Metadata,
		arg.Affinity,
	)
	var i LoreEntry
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Metadata,
		&i.Affinity,
		&i.SearchVec,
		&i.CreatedAt,
	)
	return i, err
}
