// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LoreEntry struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Content   string             `json:"content"`
	Metadata  []byte             `json:"metadata"`
	Affinity  []string           `json:"affinity"`
	SearchVec interface{}        `json:"search_vec"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LoreLink struct {
	ID         pgtype.UUID        `json:"id"`
	SourceID   pgtype.UUID        `json:"source_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Label      pgtype.Text        `json:"label"`
	IsRevealed pgtype.Bool        `json:"is_revealed"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Series struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Author      string             `json:"author"`
	CoverColor  string             `json:"cover_color"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
